version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm ci --cache .npm --prefer-offline --legacy-peer-deps
        build:
          commands:
            - REACT_APP_ENV=${REACT_APP_ENV}
            - npm run build
      artifacts:
        baseDirectory: dist
        files:
          - "**/*"
      cache:
        paths:
          - .npm/**/*
    appRoot: BigRealEstate/client
